# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktopassistant1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1245, 922)
        self.main = QtWidgets.QLabel(Form)
        self.main.setGeometry(QtCore.QRect(0, 0, 1241, 911))
        self.main.setText("")
        self.main.setPixmap(QtGui.QPixmap("images/main1.gif"))
        self.main.setScaledContents(True)
        self.main.setObjectName("main")
        self.init = QtWidgets.QLabel(Form)
        self.init.setGeometry(QtCore.QRect(170, 10, 891, 251))
        self.init.setText("")
        self.init.setPixmap(QtGui.QPixmap("images/init1.gif"))
        self.init.setScaledContents(True)
        self.init.setObjectName("init")
        self.heart = QtWidgets.QLabel(Form)
        self.heart.setGeometry(QtCore.QRect(280, 650, 681, 141))
        self.heart.setText("")
        self.heart.setPixmap(QtGui.QPixmap("images/heart.gif"))
        self.heart.setScaledContents(True)
        self.heart.setObjectName("heart")
        self.run = QtWidgets.QPushButton(Form)
        self.run.setGeometry(QtCore.QRect(20, 680, 221, 111))
        self.run.setStyleSheet("background-color: rgb(252, 255, 39);\n"
"border-color:solid  rgb(255, 90, 25);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.run.setObjectName("run")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(1002, 650, 221, 111))
        self.exit.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.run.setText(_translate("Form", "RUN"))
        self.exit.setText(_translate("Form", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
