# -- coding: utf-8 --

# Form implementation generated from reading ui file 'desktopassistant.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 613)
        self.main = QtWidgets.QLabel(Form)
        self.main.setGeometry(QtCore.QRect(0, 0, 722,613))
        self.main.setText("")
        self.main.setPixmap(QtGui.QPixmap("images/main1.gif"))
        self.main.setScaledContents(True)
        self.main.setObjectName("main")
        self.init = QtWidgets.QLabel(Form)
        self.init.setGeometry(QtCore.QRect(120, 10, 511, 181))
        self.init.setText("")
        self.init.setPixmap(QtGui.QPixmap("images/init.gif"))
        self.init.setScaledContents(True)
        self.init.setObjectName("init")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(186, 520, 361, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/heart.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.run = QtWidgets.QPushButton(Form)
        self.run.setGeometry(QtCore.QRect(20, 510, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.run.setFont(font)
        self.run.setStyleSheet("background-color: rgb(188, 255, 43);")
        self.run.setObjectName("run")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(590, 500, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.exit.setObjectName("exit")
        self.Date = QtWidgets.QLabel(Form)
        self.Date.setGeometry(QtCore.QRect(70, 180, 91, 41))
        self.Date.setText("")
        self.Date.setObjectName("Date")
        self.time = QtWidgets.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(520, 170, 121, 41))
        self.time.setObjectName("time")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.run.setText(_translate("Form", "RUN"))
        self.exit.setText(_translate("Form", "EXIT"))
        self.time.setText(_translate("Form", "TextLabel"))


if __name__ == "_main_":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())